# This workflow will do a clean installation of node dependencies, cache/restore them, and execute run scripts on the repository. This is based on the default Node.js actions.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: find openapi -name '*.json' -exec npm run bundle-deref -- {} \;
    - run: find openapi -name '*.json' -exec npm run lint-redocly -- {} \;
    - run: find openapi -name '*.json' -exec npm run lint-spectral -- {} \;
    - run: find openapi -name '*.json' -exec npm run lint-openapi -- {} \;
    - run: find openapi -name '*.json' -exec npm run codegen-java -- {} \; -exec rm -rf generated/java \;
    - run: find openapi -name '*.json' -exec npm run codegen-typescript-node -- {} \; -exec rm -rf generated/typescript-node \;
